import { CompaniesEdit } from '../../containers/index.js';
import {
  RISK_FACTORS_ACI,
  RISK_FACTORS_AMB,
  RISK_FACTORS_OTHERS,
  RISK_FACTORS_PER,
  RISK_FACTORS_FIS,
  RISK_FACTORS_QUI,
  RISK_FACTORS_BIO,
  RISK_FACTORS_ERG,
  RISK_FACTORS_INS,
  RISK_FACTORS_NOC,
  DASHBOARD,
} from '../routesNames';

import Teste from '../../Test/index.js';

const routes = [
  {
    path: RISK_FACTORS_ACI,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
  {
    path: RISK_FACTORS_AMB,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
  {
    path: RISK_FACTORS_FIS,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
  {
    path: RISK_FACTORS_QUI,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
  {
    path: RISK_FACTORS_BIO,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
  {
    path: RISK_FACTORS_INS,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
  {
    path: RISK_FACTORS_NOC,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
  {
    path: RISK_FACTORS_ERG,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
  {
    path: RISK_FACTORS_OTHERS,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
  {
    path: RISK_FACTORS_PER,
    component: Teste,
    exact: true,
    isPrivate: true,
    privateRoute: DASHBOARD,
    infoUser: ['access'],
    condition: [['admin', 'master']],
    Equal: [true],
  },
];

export default routes;
